# Configuration env

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%sql duckdb:///:memory:
%sql ATTACH IF NOT EXISTS 'data/risk.db' AS r (TYPE sqlite);

Connecting to 'duckdb:///:memory:'

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

# Analyse des tables

In [4]:
%%sql
select database, name, column_names, column_types from (show all tables) where database = 'r';

Running query in 'duckdb:///:memory:'

,database,name,column_names,column_types
0,r,mkt_forward_curve,"[as_of_date, commodity, delivery_month, price_...","[VARCHAR, VARCHAR, VARCHAR, DOUBLE]"
1,r,mkt_spot_hourly,"[commodity, delivery_hour_utc, price_eur_mwh]","[VARCHAR, VARCHAR, DOUBLE]"
2,r,pos_snapshot,"[commodity, delivery_month, book, source_syste...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, DOUBLE, V..."
3,r,ref_contract,"[contract_id, customer_id, commodity, start_da...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ..."
4,r,ref_customer,"[customer_id, customer_name, sector, segment, ...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR]"
5,r,ref_site,"[site_id, customer_id, commodity, region, dso,...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ..."
6,r,trd_deal,"[deal_id, trade_date, trade_ts, commodity, dir...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ..."

In [5]:
%%sql 
select database_name, table_name, column_count, estimated_size as n_lignes from duckdb_tables()
where database_name = 'r'
order by n_lignes desc;

Running query in 'duckdb:///:memory:'

  database_name         table_name  column_count  n_lignes
0             r    mkt_spot_hourly             3     17519
1             r           trd_deal            13      9579
2             r  mkt_forward_curve             4      9381
3             r           ref_site             8      1399
4             r       pos_snapshot             6       473
5             r       ref_contract             7       259
6             r       ref_customer             5       219

## Analyse trd_deal

In [7]:
%%sql
select * from (describe r.trd_deal);

Running query in 'duckdb:///:memory:'

       column_name column_type null   key default extra
0          deal_id     VARCHAR  YES  None    None  None
1       trade_date     VARCHAR  YES  None    None  None
2         trade_ts     VARCHAR  YES  None    None  None
3        commodity     VARCHAR  YES  None    None  None
4        direction     VARCHAR  YES  None    None  None
5   delivery_start     VARCHAR  YES  None    None  None
6     delivery_end     VARCHAR  YES  None    None  None
7       volume_mwh      DOUBLE  YES  None    None  None
8    price_eur_mwh      DOUBLE  YES  None    None  None
9     counterparty     VARCHAR  YES  None    None  None
10            book     VARCHAR  YES  None    None  None
11          status     VARCHAR  YES  None    None  None
12         version      BIGINT  YES  None    None  None

In [8]:
%%sql
select * from (summarize r.trd_deal);

Running query in 'duckdb:///:memory:'

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,deal_id,VARCHAR,D2600000,D2608999,13090,None,None,None,None,None,9580,0.0
1,trade_date,VARCHAR,2025-06-02,2026-07-24,367,None,None,None,None,None,9580,0.0
2,trade_ts,VARCHAR,2025-06-02 08:04:13,2026-07-25 13:16:03,8677,None,None,None,None,None,9580,0.0
3,commodity,VARCHAR,GAS,POWER,2,None,None,None,None,None,9580,0.0
4,direction,VARCHAR,BUY,SELL,2,None,None,None,None,None,9580,0.0
5,delivery_start,VARCHAR,2026-01-01,2027-12-01,23,None,None,None,None,None,9580,0.0
6,delivery_end,VARCHAR,2026-01-31,2028-11-30,36,None,None,None,None,None,9580,0.0
7,volume_mwh,DOUBLE,9.7,6910.4,4787,314.23159707724534,318.7419023861352,123.5933455335743,220.37963555555552,388.09233592031393,9580,0.0
8,price_eur_mwh,DOUBLE,15.694,124.153,8619,59.38184582463463,26.113370030476737,32.97382089376254,63.01423419606519,81.31263836442038,9580,0.0
9,counterparty,VARCHAR,AXPO,VITOL,12,None,None,None,None,None,9580,0.0
10,book,VARCHAR,B2B_FR_GAS_HEDGE,B2B_FR_STRUCT,5,None,None,None,None,None,9580,0.0
11,status,VARCHAR,CANCELLED,PENDING,3,None,None,None,None,None,9580,0.0
12,version,BIGINT,1,2,2,1.0566805845511482,0.23124332999835054,1,1,1,9580,0.0

In [12]:
%%sql 
select count(*) as n, 
count(distinct deal_id) as nd
from r.trd_deal;

Running query in 'duckdb:///:memory:'

      n    nd
0  9580  9000

In [19]:
%%sql 
select deal_id, count(deal_id) as n_deal
from r.trd_deal
group by deal_id
having count(deal_id) > 1

Running query in 'duckdb:///:memory:'

      deal_id  n_deal
0    D2600011       2
1    D2600374       2
2    D2600500       2
3    D2600562       2
4    D2600967       2
..        ...     ...
570  D2608284       2
571  D2608612       2
572  D2608636       2
573  D2608752       2
574  D2608919       2

[575 rows x 2 columns]

In [20]:
%%sql 
select * from (
    select deal_id, count(deal_id) as n_deal
    from r.trd_deal
    group by deal_id
    having count(deal_id) > 1
    )
where n_deal = 3

Running query in 'duckdb:///:memory:'

    deal_id  n_deal
0  D2601497       3
1  D2601680       3
2  D2600313       3
3  D2601976       3
4  D2608057       3

In [12]:
%%sql
SELECT COUNT(*)
FROM (
    SELECT *
    FROM r.trd_deal
    GROUP BY ALL
    HAVING COUNT(*) > 1
);

Running query in 'duckdb:///:memory:'

   count_star()
0            40

In [19]:
%%sql
SELECT *
FROM r.trd_deal
GROUP BY ALL
HAVING COUNT(*) > 1;

Running query in 'duckdb:///:memory:'

,deal_id,trade_date,trade_ts,commodity,direction,delivery_start,delivery_end,volume_mwh,price_eur_mwh,counterparty,book,status,version
0,D2604870,2025-07-21,2025-07-21 13:02:20,POWER,SELL,2026-02-01,2026-02-28,431.9,89.913,EDF_TRADING,B2B_FR_GAS_TRADING,CONFIRMED,1
1,D2608645,2026-05-21,2026-05-21 10:08:23,POWER,BUY,2026-12-01,2026-12-31,110.0,97.873,SHELL_ENERGY,B2B_FR_POWER_HEDGE,CONFIRMED,1
2,D2604243,2026-06-04,2026-06-04 11:52:55,GAS,BUY,2026-01-01,2026-01-31,474.1,37.518,GUNVOR,B2B_FR_GAS_HEDGE,CONFIRMED,1
3,D2606526,2025-07-07,2025-07-07 11:22:00,POWER,BUY,2026-06-01,2026-06-30,73.5,66.594,STATKRAFT,B2B_FR_POWER_HEDGE,CONFIRMED,1
4,D2600890,2025-07-31,2025-07-31 17:23:36,GAS,BUY,2026-12-01,2026-12-31,96.3,36.701,SHELL_ENERGY,B2B_FR_GAS_HEDGE,CONFIRMED,1
5,D2605509,2026-01-30,2026-01-30 13:27:34,GAS,BUY,2026-02-01,2026-02-28,394.6,40.141,RWE,B2B_FR_GAS_HEDGE,CONFIRMED,1
6,D2607350,2026-03-06,2026-03-06 09:11:02,GAS,BUY,2026-06-01,2026-08-31,695.1,25.514,STATKRAFT,B2B_FR_GAS_HEDGE,CONFIRMED,1
7,D2607639,2025-11-05,2025-11-05 13:36:28,GAS,BUY,2027-01-01,2027-01-31,98.7,41.196,UNIPER,B2B_FR_GAS_HEDGE,CONFIRMED,1
8,D2608303,2026-06-03,2026-06-03 14:23:14,GAS,BUY,2026-09-01,2026-09-30,327.0,30.684,VITOL,B2B_FR_POWER_TRADING,CONFIRMED,1
9,D2601543,2025-07-31,2025-07-31 17:04:32,POWER,BUY,2027-11-01,2027-11-30,523.7,87.376,MERCURIA,B2B_FR_POWER_HEDGE,CONFIRMED,1
10,D2602066,2025-07-24,2025-07-24 16:58:09,GAS,SELL,2026-01-01,2026-12-31,301.3,37.441,VITOL,B2B_FR_GAS_HEDGE,CONFIRMED,1
11,D2608320,2026-06-12,2026-06-12 14:16:56,POWER,SELL,2027-01-01,2027-01-31,276.8,88.113,TOTALENERGIES,B2B_FR_POWER_HEDGE,CONFIRMED,1
12,D2600313,2025-06-05,2025-06-06 08:43:30,POWER,BUY,2026-06-01,2026-06-30,185.7,68.693,STATKRAFT,B2B_FR_POWER_HEDGE,CONFIRMED,2
13,D2606212,2025-08-05,2025-08-05 13:41:33,POWER,SELL,2026-01-01,2026-01-31,605.8,73.537,SHELL_ENERGY,B2B_FR_POWER_HEDGE,CONFIRMED,1
14,D2601976,2025-07-08,2025-07-09 17:34:22,GAS,BUY,2026-12-01,2026-12-31,154.2,37.570,ICE_ENDEX,B2B_FR_GAS_HEDGE,CONFIRMED,2
15,D2604477,2025-11-27,2025-11-27 09:38:59,POWER,BUY,2027-04-01,2027-06-30,351.3,64.645,MERCURIA,B2B_FR_POWER_HEDGE,CONFIRMED,1
16,D2604596,2026-02-06,2026-02-06 15:55:44,POWER,BUY,2027-01-01,2027-01-31,284.8,96.953,MERCURIA,B2B_FR_POWER_HEDGE,CONFIRMED,1
17,D2600374,2025-08-14,2025-08-14 17:56:09,POWER,BUY,2026-11-01,2027-10-31,213.6,84.324,GUNVOR,B2B_FR_POWER_HEDGE,CONFIRMED,1
18,D2601497,2025-09-24,2025-09-24 11:53:37,POWER,SELL,2027-11-01,2027-11-30,265.3,86.853,UNIPER,B2B_FR_POWER_HEDGE,CONFIRMED,1
19,D2602367,2026-05-11,2026-05-11 11:33:06,GAS,BUY,2026-07-01,2026-07-31,1048.1,20.068,RWE,B2B_FR_GAS_HEDGE,CONFIRMED,1
20,D2604029,2026-07-03,2026-07-03 13:02:14,POWER,SELL,2027-02-01,2027-02-28,107.6,111.605,UNIPER,B2B_FR_POWER_HEDGE,CONFIRMED,1
21,D2604579,2026-05-08,2026-05-08 14:35:59,POWER,BUY,2027-03-01,2027-03-31,338.7,94.898,EDF_TRADING,B2B_FR_POWER_HEDGE,CONFIRMED,1
22,D2606095,2026-04-29,2026-04-29 13:05:11,GAS,BUY,2027-09-01,2027-11-30,197.1,24.770,ICE_ENDEX,B2B_FR_GAS_HEDGE,CONFIRMED,1
23,D2607109,2026-07-24,2026-07-24 09:33:16,GAS,BUY,2026-04-01,2026-04-30,208.9,30.160,TOTALENERGIES,B2B_FR_GAS_HEDGE,CONFIRMED,1
24,D2601680,2025-09-22,2025-09-22 14:33:01,GAS,BUY,2027-02-01,2027-02-28,85.5,36.709,RWE,B2B_FR_STRUCT,CONFIRMED,1
25,D2604421,2025-10-14,2025-10-14 13:56:18,GAS,SELL,2026-05-01,2026-05-31,408.0,28.255,EEX_CLEARED,B2B_FR_GAS_HEDGE,CONFIRMED,1
26,D2604764,2026-01-29,2026-01-29 10:57:01,POWER,SELL,2027-08-01,2027-08-31,318.4,56.579,RWE,B2B_FR_POWER_HEDGE,CONFIRMED,1
27,D2607855,2026-01-08,2026-01-08 13:05:27,POWER,SELL,2027-11-01,2027-11-30,198.2,94.574,EEX_CLEARED,B2B_FR_POWER_HEDGE,CONFIRMED,1
28,D2603362,2025-07-31,2025-07-31 16:42:23,GAS,BUY,2027-08-01,2027-08-31,67.7,23.783,RWE,B2B_FR_POWER_HEDGE,CONFIRMED,1
29,D2603681,2025-12-31,2025-12-31 16:05:50,POWER,BUY,2026-12-01,2027-02-28,255.6,102.597,TOTALENERGIES,B2B_FR_POWER_HEDGE,CONFIRMED,1
30,D2606512,2026-02-25,2026-02-25 09:36:30,POWER,BUY,2026-06-01,2026-06-30,135.9,72.343,SHELL_ENERGY,B2B_FR_POWER_HEDGE,CONFIRMED,1
31,D2600056,2026-05-15,2026-05-15 09:23:28,POWER,SELL,2026-08-01,2026-08-31,1100.4,59.182,SHELL_ENERGY,B2B_FR_POWER_HEDGE,CONFIRMED,1
32,D2600562,2026-05-06,2026-05-06 11:08:53,GAS,SELL,2026-07-01,2026-07-31,382.0,23.836,EDF_TRADING,B2B_FR_GAS_HEDGE,CONFIRMED,1
33,D2602587,2025-06-11,2025-06-11 15:09:30,POWER,BUY,2027-02-01,2027-02-28,372.3,69.079,MERCURIA,B2B_FR_POWER_HEDGE,CONFIRMED,1
34,D2608350,2026-07-08,2026-07-08 12:58:05,POWER,SELL,2026-02-01,2026-02-28,109.6,88.190,GUNVOR,B2B_FR_POWER_TRADING,CONFIRMED,1
35,D2606178,2025-08-29,2025-08-29 10:35:44,GAS,BUY,2026-03-01,2026-03-31,154.1,31.132,AXPO,B2B_FR_GAS_HEDGE,CONFIRMED,1
36,D2608057,2025-08-13,2025-08-14 14:31:18,GAS,BUY,2027-07-01,2027-09-30,73.4,24.263,AXPO,B2B_FR_GAS_HEDGE,PENDING,2
37,D2600011,2026-02-05,2026-02-05 09:00:05,POWER,SELL,2026-04-01,2026-04-30,509.6,71.105,UNIPER,B2B_FR_POWER_HEDGE,CONFIRMED,1
38,D2601010,2025-11-27,2025-11-27 14:44:43,POWER,BUY,2027-04-01,2027-04-30,679.0,82.096,MERCURIA,B2B_FR_POWER_HEDGE,CONFIRMED,1
39,D2604483,2026-05-19,2026-05-19 17:23:03,POWER,BUY,2027-02-01,2027-02-28,1621.6,84.406,MERCURIA,B2B_FR_POWER_HEDGE,CONFIRMED,1