In [1]:
import pandas as pd

In [2]:
from pathlib import Path
import os

# remonte jusqu'au dossier qui contient .git, puis s'y place
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / ".git").is_dir())
os.chdir(ROOT)
print("racine projet :", ROOT)

racine projet : /Users/benjaminscemama/dev/market-risk-control

In [3]:
%load_ext sql
%config SqlMagic.autopandas = True
%sql duckdb:///:memory:
%sql ATTACH IF NOT EXISTS 'data/risk.db' AS r (TYPE sqlite);

Connecting to 'duckdb:///:memory:'

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [4]:
%%sql
-- Test configuration environnement
SELECT name FROM (SHOW ALL TABLES) WHERE database = 'r' ORDER BY name;

Running query in 'duckdb:///:memory:'

                name
0  mkt_forward_curve
1    mkt_spot_hourly
2       pos_snapshot
3       ref_contract
4       ref_customer
5           ref_site
6           trd_deal

In [5]:
df = %sql select * from r.trd_deal;
df['deal_id'].value_counts().value_counts()

Running query in 'duckdb:///:memory:'

count
1    8425
2     570
3       5
Name: count, dtype: int64